export const locations = [
  {
    name: 'Albany',
    lat: 42.6526,
    lng: -73.7562,
    address: 'Albany, NY',
    state: 'NY',
    calendarId: '',
  },
  {
    name: 'Baton Rouge',
    lat: 30.4515,
    lng: -91.1871,
    address: 'Baton Rouge, LA',
    state: 'LA',
    calendarId: 'GlF9BnIfY7PK0GRakQpp',
  },
  {
    name: 'Bloomington',
    lat: 40.4842,
    lng: -88.9937,
    address: 'Bloomington, IL',
    state: 'IL',
    calendarId: '',
  },
  {
    name: 'Boston North Shore',
    lat: 42.465,
    lng: -70.9495,
    address: 'Boston North Shore, MA',
    state: 'MA',
    calendarId: '',
  },
  {
    name: 'Chicago North',
    lat: 42.0451,
    lng: -87.6877,
    address: 'Chicago North, IL',
    state: 'IL',
    calendarId: '',
  },
  {
    name: 'Chicago South',
    lat: 41.7508,
    lng: -87.6318,
    address: 'Chicago South, IL',
    state: 'IL',
    calendarId: '',
  },
  {
    name: 'Corpus Christi',
    lat: 27.8006,
    lng: -97.3964,
    address: 'Corpus Christi, TX',
    state: 'TX',
    calendarId: '',
  },
  { name: 'DC West', lat: 38.9072, lng: -77.0369, address: 'DC West', state: 'DC', calendarId: '' },
  { name: 'DFW', lat: 32.7767, lng: -96.797, address: 'DFW, TX', state: 'TX', calendarId: '' },
  {
    name: 'Harrisburg',
    lat: 40.2732,
    lng: -76.8867,
    address: 'Harrisburg, PA',
    state: 'PA',
    calendarId: '',
  },
  {
    name: 'Hartford',
    lat: 41.7637,
    lng: -72.6851,
    address: 'Hartford, CT',
    state: 'CT',
    calendarId: '',
  },
  {
    name: 'Lafayette',
    lat: 30.2241,
    lng: -92.0198,
    address: 'Lafayette, LA',
    state: 'LA',
    calendarId: '',
  },
  {
    name: 'Lexington',
    lat: 38.0406,
    lng: -84.5037,
    address: 'Lexington, KY',
    state: 'KY',
    calendarId: '',
  },
  {
    name: 'Long Island',
    lat: 40.7891,
    lng: -73.1349,
    address: 'Long Island, NY',
    state: 'NY',
    calendarId: '',
  },
  {
    name: 'Lubbock',
    lat: 33.5779,
    lng: -101.8552,
    address: 'Lubbock, TX',
    state: 'TX',
    calendarId: '',
  },
  {
    name: 'Manchester',
    lat: 42.9956,
    lng: -71.4548,
    address: 'Manchester, NH',
    state: 'NH',
    calendarId: '',
  },
  {
    name: 'McAllen',
    lat: 26.2034,
    lng: -98.23,
    address: 'McAllen, TX',
    state: 'TX',
    calendarId: '',
  },
  {
    name: 'Midland',
    lat: 31.9974,
    lng: -102.0779,
    address: 'Midland, TX',
    state: 'TX',
    calendarId: '',
  },
  {
    name: 'New Jersey',
    lat: 40.0583,
    lng: -74.4057,
    address: 'New Jersey, NJ',
    state: 'NJ',
    calendarId: '',
  },
  {
    name: 'Northshore',
    lat: 30.5052,
    lng: -90.0895,
    address: 'Northshore, LA',
    state: 'LA',
    calendarId: '',
  },
  {
    name: 'Orlando',
    lat: 28.5383,
    lng: -81.3792,
    address: 'Orlando, FL',
    state: 'FL',
    calendarId: '',
  },
  {
    name: 'Oxford',
    lat: 41.4253,
    lng: -73.1164,
    address: 'Oxford, CT',
    state: 'CT',
    calendarId: '',
  },
  {
    name: 'Pittsburgh',
    lat: 40.4406,
    lng: -79.9959,
    address: 'Pittsburgh, PA',
    state: 'PA',
    calendarId: '',
  },
  {
    name: 'Providence',
    lat: 41.824,
    lng: -71.4128,
    address: 'Providence, RI',
    state: 'RI',
    calendarId: '',
  },
  {
    name: 'Raleigh',
    lat: 35.7796,
    lng: -78.6382,
    address: 'Raleigh, NC',
    state: 'NC',
    calendarId: '',
  },
  {
    name: 'Virginia Beach',
    lat: 36.8529,
    lng: -75.978,
    address: 'Virginia Beach, VA',
    state: 'VA',
    calendarId: '',
  },
  {
    name: 'Westchester',
    lat: 41.122,
    lng: -73.7949,
    address: 'Westchester, NY',
    state: 'NY',
    calendarId: 'TIznRuQ73SfQq1sDKTZu',
  },
];

export const progressFormFields = [
  // General Information
  {
    name: 'reportDate',
    label: 'Report Date',
    type: 'date',
    required: true,
    tooltip: 'Select the date of the report',
    category: 'General Information',
    gridSpan: 12,
  },
  {
    name: 'location',
    label: 'Office Location',
    type: 'select',
    required: true,
    options: locations.map((location) => location.name),
    tooltip: 'Choose the office location where you worked',
    category: 'General Information',
    gridSpan: 12,
  },
  {
    name: 'firstName',
    label: 'First Name',
    type: 'text',
    required: true,
    category: 'General Information',
    gridSpan: 12,
  },
  {
    name: 'lastName',
    label: 'Last Name',
    type: 'text',
    required: true,
    category: 'General Information',
    gridSpan: 12,
  },

  // Effort and Outcome
  {
    name: 'doorsKnocked',
    label: 'Doors Knocked',
    type: 'select',
    required: true,
    tooltip: 'Enter the number of doors you knocked today',
    category: 'Effort and Outcome',
    gridSpan: 24,
    placeholder: 'How many doors did you knock today?',
    options: Array.from({ length: 21 }, (_, i) => i),
    isExpandable: true,
  },
  {
    name: 'appointmentsScheduled',
    label: 'Appointments Scheduled from Knocking',
    type: 'select',
    required: true,
    tooltip: 'Enter the number of appointments you scheduled from knocking these doors',
    category: 'Effort and Outcome',
    gridSpan: 24,
    placeholder: 'How many appointments did you schedule today?',
    options: Array.from({ length: 10 }, (_, i) => i),
  },
  {
    name: 'inspectionsScheduled',
    label: 'Inspections Scheduled',
    type: 'select',
    required: true,
    tooltip: 'Enter the number of inspections you scheduled today',
    category: 'Effort and Outcome',
    gridSpan: 24,
    placeholder: 'How many inspection you have scheduled today',
    options: Array.from({ length: 21 }, (_, i) => i),
    isExpandable: true,
  },
  {
    name: 'companyLeadsReceived',
    label: 'Company Leads Received',
    type: 'select',
    required: true,
    tooltip: 'Select the number of company-provided leads you received today',
    category: 'Effort and Outcome',
    gridSpan: 24,
    placeholder: 'How many leads have you received today?',
    options: Array.from({ length: 21 }, (_, i) => i),
    isExpandable: true,
  },
];

export const inspectionOutcomeOptions = [
  { value: 'closed', label: 'Closed/Sold' },
  { value: 'notClosed', label: "Didn't close" },
];

export const outcomeOptions = [
  { value: 'noShow', label: 'No show' },
  { value: 'completedInspection', label: 'Completed inspection' },
  { value: 'alreadyHasService', label: 'Already has service' },
  { value: 'renterMultiFamily', label: 'Renter/Multi-family' },
  { value: 'knockOut', label: 'Knock-out' },
  { value: 'turnedAway', label: 'Turned away' },
];
export const negativeOutComeReasons = [
  { value: 'money', label: 'Money' },
  { value: 'unsatisfiedCustomer', label: 'Unsatisfied Customer' },
  { value: 'noDecisionMaker', label: 'No decision maker' },
  { value: 'moving', label: 'Moving' },
  { value: 'newBuild', label: 'New build' },
  { value: 'noValue', label: 'No value' },
];

export const closedOptions = [
  { value: 'initialInstallCharged', label: 'Initial Install Charged' },
  { value: 'monthlyRecurringPayment', label: 'Monthly Recurring Payment' },
  { value: 'scheduledInstallDate', label: 'Scheduled Install Date' },
];

export const progressFormFieldsComm = [
  // {
  //   name: 'self_gen_scheduled',
  //   label: 'Self-Gen Inspections Scheduled',
  //   type: 'select',
  //   required: true,
  //   tooltip: 'Enter the number of self-generated inspections scheduled for today',
  //   category: 'Effort and Outcome',
  //   gridSpan: 24,
  //   options: Array.from({ length: 21 }, (_, i) => i),
  // },
  // {
  //   name: 'self_gen_completed',
  //   label: 'Self-Gen Inspections Completed',
  //   type: 'select',
  //   required: true,
  //   tooltip: 'Enter the number of self-generated inspections you completed today',
  //   category: 'Effort and Outcome',
  //   gridSpan: 24,
  //   options: Array.from({ length: 21 }, (_, i) => i),
  // },
  // {
  //   name: 'self_gen_closed',
  //   label: 'Self-Gen Inspections Closed',
  //   type: 'select',
  //   required: true,
  //   tooltip: 'Select the number of self-generated inspections you closed today',
  //   category: 'Effort and Outcome',
  //   gridSpan: 24,
  //   options: Array.from({ length: 21 }, (_, i) => i),
  // },
  // {
  //   name: 'appointments_completed',
  //   label: 'Appointments Completed',
  //   type: 'select',
  //   required: true,
  //   tooltip: 'Select the number of appointments you completed today',
  //   category: 'Effort and Outcome',
  //   gridSpan: 24,
  //   options: Array.from({ length: 21 }, (_, i) => i),
  // },
  // {
  //   name: 'company_leads_closed',
  //   label: 'Company Leads Closed',
  //   type: 'select',
  //   required: true,
  //   tooltip: 'Select the number of company leads you closed today',
  //   category: 'Effort and Outcome',
  //   gridSpan: 24,
  //   options: Array.from({ length: 21 }, (_, i) => i),
  // },
];
