export const locations = [
  {
    name: 'Albany',
    lat: 42.6526,
    lng: -73.7562,
    address: 'Albany, NY',
    state: 'NY',
    calendarId: '',
  },
  {
    name: 'Baton Rouge',
    lat: 30.4515,
    lng: -91.1871,
    address: 'Baton Rouge, LA',
    state: 'LA',
    calendarId: 'GlF9BnIfY7PK0GRakQpp',
  },
  {
    name: 'Bloomington',
    lat: 40.4842,
    lng: -88.9937,
    address: 'Bloomington, IL',
    state: 'IL',
    calendarId: '',
  },
  {
    name: 'Boston North Shore',
    lat: 42.465,
    lng: -70.9495,
    address: 'Boston North Shore, MA',
    state: 'MA',
    calendarId: '',
  },
  {
    name: 'Chicago North',
    lat: 42.0451,
    lng: -87.6877,
    address: 'Chicago North, IL',
    state: 'IL',
    calendarId: '',
  },
  {
    name: 'Chicago South',
    lat: 41.7508,
    lng: -87.6318,
    address: 'Chicago South, IL',
    state: 'IL',
    calendarId: '',
  },
  {
    name: 'Corpus Christi',
    lat: 27.8006,
    lng: -97.3964,
    address: 'Corpus Christi, TX',
    state: 'TX',
    calendarId: '',
  },
  { name: 'DC West', lat: 38.9072, lng: -77.0369, address: 'DC West', state: 'DC', calendarId: '' },
  { name: 'DFW', lat: 32.7767, lng: -96.797, address: 'DFW, TX', state: 'TX', calendarId: '' },
  {
    name: 'Harrisburg',
    lat: 40.2732,
    lng: -76.8867,
    address: 'Harrisburg, PA',
    state: 'PA',
    calendarId: '',
  },
  {
    name: 'Hartford',
    lat: 41.7637,
    lng: -72.6851,
    address: 'Hartford, CT',
    state: 'CT',
    calendarId: '',
  },
  {
    name: 'Lafayette',
    lat: 30.2241,
    lng: -92.0198,
    address: 'Lafayette, LA',
    state: 'LA',
    calendarId: '',
  },
  {
    name: 'Lexington',
    lat: 38.0406,
    lng: -84.5037,
    address: 'Lexington, KY',
    state: 'KY',
    calendarId: '',
  },
  {
    name: 'Long Island',
    lat: 40.7891,
    lng: -73.1349,
    address: 'Long Island, NY',
    state: 'NY',
    calendarId: '',
  },
  {
    name: 'Lubbock',
    lat: 33.5779,
    lng: -101.8552,
    address: 'Lubbock, TX',
    state: 'TX',
    calendarId: '',
  },
  {
    name: 'Manchester',
    lat: 42.9956,
    lng: -71.4548,
    address: 'Manchester, NH',
    state: 'NH',
    calendarId: '',
  },
  {
    name: 'McAllen',
    lat: 26.2034,
    lng: -98.23,
    address: 'McAllen, TX',
    state: 'TX',
    calendarId: '',
  },
  {
    name: 'Midland',
    lat: 31.9974,
    lng: -102.0779,
    address: 'Midland, TX',
    state: 'TX',
    calendarId: '',
  },
  {
    name: 'New Jersey',
    lat: 40.0583,
    lng: -74.4057,
    address: 'New Jersey, NJ',
    state: 'NJ',
    calendarId: '',
  },
  {
    name: 'Northshore',
    lat: 30.5052,
    lng: -90.0895,
    address: 'Northshore, LA',
    state: 'LA',
    calendarId: '',
  },
  {
    name: 'Orlando',
    lat: 28.5383,
    lng: -81.3792,
    address: 'Orlando, FL',
    state: 'FL',
    calendarId: '',
  },
  {
    name: 'Oxford',
    lat: 41.4253,
    lng: -73.1164,
    address: 'Oxford, CT',
    state: 'CT',
    calendarId: '',
  },
  {
    name: 'Pittsburgh',
    lat: 40.4406,
    lng: -79.9959,
    address: 'Pittsburgh, PA',
    state: 'PA',
    calendarId: '',
  },
  {
    name: 'Providence',
    lat: 41.824,
    lng: -71.4128,
    address: 'Providence, RI',
    state: 'RI',
    calendarId: '',
  },
  {
    name: 'Raleigh',
    lat: 35.7796,
    lng: -78.6382,
    address: 'Raleigh, NC',
    state: 'NC',
    calendarId: '',
  },
  {
    name: 'Virginia Beach',
    lat: 36.8529,
    lng: -75.978,
    address: 'Virginia Beach, VA',
    state: 'VA',
    calendarId: '',
  },
  {
    name: 'Westchester',
    lat: 41.122,
    lng: -73.7949,
    address: 'Westchester, NY',
    state: 'NY',
    calendarId: 'TIznRuQ73SfQq1sDKTZu',
  },
];

export const progressFormFields = [
  // General Information
  {
    name: 'reportDate',
    label: 'Report Date',
    type: 'date',
    required: true,
    tooltip: 'Select the date of the report',
    category: 'General Information',
    gridSpan: 12,
  },
  {
    name: 'location',
    label: 'Office Location',
    type: 'select',
    required: true,
    options: locations.map((location) => location.name),
    tooltip: 'Choose the office location where you worked',
    category: 'General Information',
    gridSpan: 12,
  },
  {
    name: 'first_name',
    label: 'First Name',
    type: 'text',
    required: true,
    tooltip: 'Enter your first name',
    category: 'General Information',
    gridSpan: 12,
  },
  {
    name: 'last_name',
    label: 'Last Name',
    type: 'text',
    required: true,
    tooltip: 'Enter your last name',
    category: 'General Information',
    gridSpan: 12,
  },

  // Effort and Outcome
  {
    name: 'doors_knocked',
    label: 'Doors Knocked',
    type: 'select',
    required: true,
    tooltip: 'Enter the number of doors you knocked today',
    category: 'Effort and Outcome',
    gridSpan: 24,
    options: Array.from({ length: 21 }, (_, i) => i),
  },
  {
    name: 'inspections_scheduled',
    label: 'Inspections Scheduled',
    type: 'select',
    required: true,
    tooltip: 'Enter the number of inspections you scheduled today',
    category: 'Effort and Outcome',
    gridSpan: 24,
    options: Array.from({ length: 21 }, (_, i) => i),
  },
  {
    name: 'self_gen_scheduled',
    label: 'Self-Gen Inspections Scheduled',
    type: 'select',
    required: true,
    tooltip: 'Enter the number of self-generated inspections scheduled for today',
    category: 'Effort and Outcome',
    gridSpan: 24,
    options: Array.from({ length: 21 }, (_, i) => i),
  },
  {
    name: 'self_gen_completed',
    label: 'Self-Gen Inspections Completed',
    type: 'select',
    required: true,
    tooltip: 'Enter the number of self-generated inspections you completed today',
    category: 'Effort and Outcome',
    gridSpan: 24,
    options: Array.from({ length: 21 }, (_, i) => i),
  },
  {
    name: 'self_gen_closed',
    label: 'Self-Gen Inspections Closed',
    type: 'select',
    required: true,
    tooltip: 'Select the number of self-generated inspections you closed today',
    category: 'Effort and Outcome',
    gridSpan: 24,
    options: Array.from({ length: 21 }, (_, i) => i),
  },
  {
    name: 'company_leads_received',
    label: 'Company Leads Received',
    type: 'select',
    required: true,
    tooltip: 'Select the number of company-provided leads you received today',
    category: 'Effort and Outcome',
    gridSpan: 24,
    options: Array.from({ length: 21 }, (_, i) => i),
  },
  {
    name: 'appointments_completed',
    label: 'Appointments Completed',
    type: 'select',
    required: true,
    tooltip: 'Select the number of appointments you completed today',
    category: 'Effort and Outcome',
    gridSpan: 24,
    options: Array.from({ length: 21 }, (_, i) => i),
  },
  {
    name: 'company_leads_closed',
    label: 'Company Leads Closed',
    type: 'select',
    required: true,
    tooltip: 'Select the number of company leads you closed today',
    category: 'Effort and Outcome',
    gridSpan: 24,
    options: Array.from({ length: 21 }, (_, i) => i),
  },
  {
    name: 'time_studied_today',
    label: 'Time Studied Today',
    type: 'select',
    required: true,
    tooltip: 'How many hours did you study today?',
    category: 'Effort and Outcome',
    gridSpan: 24,
    options: [0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5],
  },
  {
    name: 'hardestObjection',
    label: 'Hardest Objection',
    type: 'text',
    required: false,
    tooltip: 'Describe the hardest objection you overcame today',
    category: 'Effort and Outcome',
    gridSpan: 24,
  },
];
